//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using DAL.Interfaces;
    using System;
    using System.Collections.Generic;
    
    public partial class Hotels: IReturnId
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotels()
        {
            this.ImagesHotels = new HashSet<ImagesHotels>();
        }
    
        public int Id { get; set; }
        public string HotelsName { get; set; }
        public Nullable<int> CityId { get; set; }
        public decimal PriceDay { get; set; }
        public int Stars { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagesHotels> ImagesHotels { get; set; }

        public int GetId()
        {
            return Id;
        }
    }
}
