//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using DAL.Interfaces;
    using System;
    using System.Collections.Generic;
    
    public partial class ImagesShowPlace: IReturnId
    {
        public int Id { get; set; }
        public string ImageURL { get; set; }
        public Nullable<int> ShowPlaceId { get; set; }
    
        public virtual ShowPlace ShowPlace { get; set; }

        public int GetId()
        {
            return Id;
        }
    }
}
