//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponsibleForTheTours
    {
        public int Id { get; set; }
        public Nullable<int> ToursId { get; set; }
        public Nullable<int> AgencyWorkerId { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Tours Tours { get; set; }
    }
}
