//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.TAContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagesHotels
    {
        public int Id { get; set; }
        public string ImageURL { get; set; }
        public Nullable<int> HotelsId { get; set; }
    
        public virtual Hotels Hotels { get; set; }
    }
}
