//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.TAContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointInTour
    {
        public int Id { get; set; }
        public Nullable<int> ShowPlaceId { get; set; }
        public Nullable<int> ToursId { get; set; }
        public System.DateTime DateOfVisit { get; set; }
        public bool IsPriceInTours { get; set; }
    
        public virtual ShowPlace ShowPlace { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
