//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.TAContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelAgencyEntities : DbContext
    {
        public TravelAgencyEntities()
            : base("name=TravelAgencyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgencyWorker> AgencyWorkers { get; set; }
        public virtual DbSet<ArchiveOfEndedTour> ArchiveOfEndedTours { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<ImagesHotel> ImagesHotels { get; set; }
        public virtual DbSet<ImagesShowPlace> ImagesShowPlaces { get; set; }
        public virtual DbSet<ListClientShowInfoTour> ListClientShowInfoTours { get; set; }
        public virtual DbSet<ListOfTouristBuy> ListOfTouristBuys { get; set; }
        public virtual DbSet<PointInTour> PointInTours { get; set; }
        public virtual DbSet<ResponsibleForTheCountry> ResponsibleForTheCountries { get; set; }
        public virtual DbSet<ResponsibleForTheTour> ResponsibleForTheTours { get; set; }
        public virtual DbSet<ShowPlace> ShowPlaces { get; set; }
        public virtual DbSet<Tour> Tours { get; set; }
        public virtual DbSet<WaysInTour> WaysInTours { get; set; }
        public virtual DbSet<WaysOfTransportation> WaysOfTransportations { get; set; }
    }
}
