//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.TAContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelAgencyEntities : DbContext
    {
        public TravelAgencyEntities()
            : base("name=TravelAgencyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgencyWorker> AgencyWorker { get; set; }
        public virtual DbSet<ArchiveOfEndedTours> ArchiveOfEndedTours { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Hotels> Hotels { get; set; }
        public virtual DbSet<ImagesHotels> ImagesHotels { get; set; }
        public virtual DbSet<ImagesShowPlace> ImagesShowPlace { get; set; }
        public virtual DbSet<ListClientShowInfoTour> ListClientShowInfoTour { get; set; }
        public virtual DbSet<ListOfTouristBuy> ListOfTouristBuy { get; set; }
        public virtual DbSet<PointInTours> PointInTours { get; set; }
        public virtual DbSet<ResponsibleForTheTours> ResponsibleForTheTours { get; set; }
        public virtual DbSet<ShowPlace> ShowPlace { get; set; }
        public virtual DbSet<Tours> Tours { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WaysInTours> WaysInTours { get; set; }
        public virtual DbSet<WaysOfTransportation> WaysOfTransportation { get; set; }
    }
}
